-- lua/core/domain/icons.lua
-- Layer 2 domain: single source of truth for all glyphs / symbols.
-- Used by LTOS commands and adapters. config/icons.lua re-exports this for app layer.
-- M-04: Consolidated ft/file/extension icon mappings

return {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  fold = {
    open = " ",
    close = " ",
  },
  todo = {
    FIX = " ",
    TODO = " ",
    HACK = " ",
    WARN = " ",
    PERF = " ",
    NOTE = " ",
    TEST = " ",
  },
  ft = {
    -- Programming languages
    lua = " ",
    python = " ",
    rust = " ",
    go = " ",
    typescript = " ",
    javascript = " ",
    tsx = " ",
    jsx = " ",
    html = " ",
    css = " ",
    scss = " ",
    markdown = " ",
    yaml = " ",
    json = " ",
    toml = " ",
    sh = " ",
    bash = " ",
    zsh = " ",
    fish = " ",
    c = " ",
    cpp = " ",
    java = " ",
    kotlin = " ",
    swift = " ",
    ruby = " ",
    php = " ",
    elixir = " ",
    clojure = " ",
    asm = " ",
    nix = " ",
    -- Config files
    vim = " ",
    git = " ",
    docker = " ",
    -- Other
    text = " ",
    conf = " ",
  },
  file = {
    [".env"] = { glyph = " ", hl = "MiniIconsYellow" },
    [".envrc"] = { glyph = " ", hl = "MiniIconsYellow" },
    [".gitignore"] = { glyph = " ", hl = "MiniIconsRed" },
    [".gitconfig"] = { glyph = " ", hl = "MiniIconsRed" },
    [".keep"] = { glyph = "󰊢 ", hl = "MiniIconsGrey" },
    ["devcontainer.json"] = { glyph = " ", hl = "MiniIconsAzure" },
    ["Makefile"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["Dockerfile"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["docker-compose.yml"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["package.json"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["package-lock.json"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["yarn.lock"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["pnpm-lock.yaml"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["Cargo.toml"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["Cargo.lock"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["go.mod"] = { glyph = " ", hl = "MiniIconsCyan" },
    ["go.sum"] = { glyph = " ", hl = "MiniIconsCyan" },
    ["requirements.txt"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["setup.py"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["pyproject.toml"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["init.lua"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["init.vim"] = { glyph = " ", hl = "MiniIconsGreen" },
  },
  extension = {
    -- Programming
    ["lua"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["py"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["pyc"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["rs"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["go"] = { glyph = " ", hl = "MiniIconsCyan" },
    ["ts"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["tsx"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["js"] = { glyph = " ", hl = "MiniIconsYellow" },
    ["jsx"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["html"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["htm"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["css"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["scss"] = { glyph = " ", hl = "MiniIconsPink" },
    ["sass"] = { glyph = " ", hl = "MiniIconsPink" },
    ["less"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["md"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["markdown"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["yaml"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["yml"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["json"] = { glyph = " ", hl = "MiniIconsYellow" },
    ["jsonc"] = { glyph = " ", hl = "MiniIconsYellow" },
    ["toml"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["sh"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["bash"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["zsh"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["fish"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["c"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["h"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["cpp"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["hpp"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["cc"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["cxx"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["java"] = { glyph = " ", hl = "MiniIconsRed" },
    ["kt"] = { glyph = " ", hl = "MiniIconsPurple" },
    ["kts"] = { glyph = " ", hl = "MiniIconsPurple" },
    ["swift"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["rb"] = { glyph = " ", hl = "MiniIconsRed" },
    ["erb"] = { glyph = " ", hl = "MiniIconsRed" },
    ["php"] = { glyph = " ", hl = "MiniIconsPurple" },
    ["ex"] = { glyph = " ", hl = "MiniIconsPurple" },
    ["exs"] = { glyph = " ", hl = "MiniIconsPurple" },
    ["clj"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["cljc"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["cljs"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["asm"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["s"] = { glyph = " ", hl = "MiniIconsOrange" },
    ["nix"] = { glyph = " ", hl = "MiniIconsBlue" },
    -- Config
    ["vim"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["vimrc"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["nvim"] = { glyph = " ", hl = "MiniIconsGreen" },
    ["git"] = { glyph = " ", hl = "MiniIconsRed" },
    ["dockerfile"] = { glyph = " ", hl = "MiniIconsBlue" },
    ["txt"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["conf"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["cfg"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["ini"] = { glyph = " ", hl = "MiniIconsGrey" },
    -- Images
    ["png"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["jpg"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["jpeg"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["gif"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["svg"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["ico"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["webp"] = { glyph = "󰉏 ", hl = "MiniIconsGrey" },
    ["iso"] = { glyph = " ", hl = "MiniIconsGrey" },
    -- Fonts
    ["ttf"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["otf"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["woff"] = { glyph = " ", hl = "MiniIconsGrey" },
    ["woff2"] = { glyph = " ", hl = "MiniIconsGrey" },
    -- Audio
    ["mp3"] = { glyph = "󰎈 ", hl = "MiniIconsGrey" },
    ["wav"] = { glyph = "󰎈 ", hl = "MiniIconsGrey" },
    ["flac"] = { glyph = "󰎈 ", hl = "MiniIconsGrey" },
    ["ogg"] = { glyph = "󰎈 ", hl = "MiniIconsGrey" },
    -- Video
    ["mp4"] = { glyph = "󰎆 ", hl = "MiniIconsGrey" },
    ["mkv"] = { glyph = "󰎆 ", hl = "MiniIconsGrey" },
    ["avi"] = { glyph = "󰎆 ", hl = "MiniIconsGrey" },
    ["mov"] = { glyph = "󰎆 ", hl = "MiniIconsGrey" },
    -- Archives
    ["zip"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["tar"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["gz"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["bz2"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["xz"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["7z"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    ["rar"] = { glyph = "󰜢 ", hl = "MiniIconsGrey" },
    -- Lock files
    ["lock"] = { glyph = "", hl = "MiniIconsGrey" },
    -- Images
    ["img"] = { glyph = " ", hl = "MiniIconsGrey" },
  },
}
